### ISSUE TITLE
Crash: Listener already in use

### ISSUE THREAD

**Issue by Nikita22007** [Nikita22007/pixel-dungeon-multiplayer#4]
```
 ERROR LOG 
java.lang.IllegalArgumentException: listener already in use
    at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)
    at android.net.nsd.NsdManager.putListener(NsdManager.java:448)
    at android.net.nsd.NsdManager.resolveService(NsdManager.java:616)
    at com.watabou.pixeldungeon.network.NSD$2.onServiceFound(NSD.java:141)
    at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:387)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:192)
    at android.os.HandlerThread.run(HandlerThread.java:65)
 ```
 The problem occurs when trying to enter the search server interface after selecting a hero.

**Comment by Nikita22007** [comment]
https://stackoverflow.com/questions/25815162/listener-already-in-use-service-discovery

**Comment by Nikita22007** [comment]
https://developer.android.com/training/connect-devices-wirelessly/nsd

**Comment by Nikita22007** [comment]
In API versions <= 19, there is no entirely reliable way to know when a listener may be re-used, and a new listener should be created for each service discovery request
