### ISSUE TITLE
Android 12 Start Game in Crash.

### ISSUE THREAD

**Issue by LingASDJ** [Nikita22007/pixel-dungeon-multiplayer#5]
java.lang.IllegalArgumentException: listener already in use
    at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)
    at android.net.nsd.NsdManager.putListener(NsdManager.java:448)
    at android.net.nsd.NsdManager.resolveService(NsdManager.java:616)
    at com.watabou.pixeldungeon.network.NSD$2.onServiceFound(NSD.java:141)
    at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:387)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:192)
    at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by LingASDJ** [comment]
a duplicate bug commit
